services:
  - type: web
    name: Freshdesk
    env: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        sync: false
      - key: FRESHDESK_API_KEY
        fromDatabase: true
      - key: FRESHDESK_DOMAIN
        fromDatabase: true
